baseURL = "/"
languageCode = "de-de"

title = "Christina Brieger"

## Site Settings
[params]
author = "Martin Brieger"
description = "Architektin"

## Site Meta Settings
[params.meta]
description = "Architekt Architektin Rosenheim"
keywords = "Architekt, Architektin, Rosenheim, Architektur, Entwurf, Planung, Brieger, Christina"

## Social Accounts
[params.social]
email = "architektur@christina-brieger.de"

## Extras
[params.extra]
copyright = "by Martin Brieger Â© 2019"